output_name: test_000

output_dir:
  result: /home/yuxiang/liao/workspace/arrg_img2text/outputs/results
  model: /home/yuxiang/liao/workspace/arrg_img2text/outputs/models
  checkpoint: /home/yuxiang/liao/workspace/arrg_img2text/outputs/checkpoints
  log: /home/yuxiang/liao/workspace/arrg_img2text/outputs/logs

data_path:
  mimic: /home/yuxiang/liao/resources/datasets/mimic-cxr
  interpret: /home/yuxiang/liao/resources/datasets/interpret-cxr
  interpret-test-public: /home/yuxiang/liao/resources/datasets/interpret-cxr-test-public
  custom_text: /home/yuxiang/liao/workspace/arrg_preprocessing/outputs/interpret_text_exp/interpret_text_findings_effusion

target_section: findings

mlflow_url: "http://localhost:6006" # mlflow server --host 127.0.0.1 --port 6006
max_checkpoints_to_keep: 3

model_name_or_path:
  clip: /home/yuxiang/liao/resources/downloaded_models/clip-vit-base-patch32
  swinv2: /home/yuxiang/liao/resources/downloaded_models/swinv2-base-patch4-window8-256

# The image processor depends on the model.vision_backbone
preprocess_dataset: False
preprocess:
  image_processor: swinv2
  cache_path: /home/yuxiang/liao/workspace/arrg_img2text/dataset_cache/swinv2base_rbg256 #clipbase_rbg224
  batched: True
  batch_size: 64
  num_proc: 16

# path to checkpoint or, bool;
# if True, then use the latest checkpoint from `output_dir.checkpoint/output_name`
resume_from_checkpoint: False
do_train: True
# if do_test=True, it will load the best pre_trained model saved at `output_dir.model/output_name`, and eval the model on test set.
do_test: True
use_debug_subset: True

model:
  vision_backbone: swinv2
  num_classes: 1

train:
  seed: 42
  batch_size: 8
  num_epochs: 10
  grad_accum_steps: 2
  warmup_proportion: 0.1
  weight_decay: 0.0
  lr: 0.00001
  mlc_lr: 0.00001
  clip_grad_norm: 1.0
  mixed_precision: bf16 # ‘no’,‘fp16’,‘bf16’. bf16 for A100 and cpu, fp16 for V100

  print_loss_per_n_steps: 1
  eval_per_steps: 2

eval:
  batch_size: 32
